<?php
/**
 * @author <PPWD/> - Pro Products Web Development
 * @copyright 2024 - Pro Products Web Development. All rights reserved.
 * @package ppwd/module-base
 */
?>
<script>
    requirejs(['jquery' ],
        function ($) {
            $(document).ready(function() {
                $('li[data-ui-id="menu-ppwd-base-documentation"] a').attr('href', 'https://www.proproductswebdevelopment.com/services/adobe-commerce.htm').attr('target', '_blank');
                $('li[data-ui-id="menu-ppwd-base-marketplace"] a').attr('href', 'https://commercemarketplace.adobe.com/partner/ProProducts').attr('target', '_blank');
            });
        });
</script>